"""initial schema

Revision ID: ea540c89c430
Revises:
Create Date: 2026-09-11 14:05:37.767071
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "ea540c89c430"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "country_profiles",
        sa.Column("country_code", sa.String(length=2), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("default_language", sa.String(length=5), nullable=False),
        sa.Column("road_context", sa.JSON(), nullable=False),
        sa.Column("supply_context", sa.JSON(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_demo", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_country_profiles")),
    )
    op.create_index(
        op.f("ix_country_profiles_country_code"), "country_profiles", ["country_code"], unique=True
    )
    op.create_table(
        "source_records",
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("publisher", sa.String(length=200), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("source_type", sa.String(length=80), nullable=False),
        sa.Column("market", sa.String(length=2), nullable=True),
        sa.Column("language", sa.String(length=5), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "confidence",
            sa.Enum("LOW", "MEDIUM", "HIGH", name="source_confidence", native_enum=False),
            nullable=False,
        ),
        sa.Column(
            "usage_status",
            sa.Enum(
                "ACTIVE",
                "REVIEW_REQUIRED",
                "DISABLED",
                name="source_usage_status",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("is_demo", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_source_records")),
    )
    op.create_index(op.f("ix_source_records_is_demo"), "source_records", ["is_demo"], unique=False)
    op.create_index(op.f("ix_source_records_market"), "source_records", ["market"], unique=False)
    op.create_index(
        op.f("ix_source_records_source_type"), "source_records", ["source_type"], unique=False
    )
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("password_hash", sa.String(length=512), nullable=False),
        sa.Column("preferred_language", sa.String(length=5), nullable=False),
        sa.Column("country_code", sa.String(length=2), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_admin", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "vehicle_makes",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("normalized_name", sa.String(length=120), nullable=False),
        sa.Column("is_demo", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vehicle_makes")),
    )
    op.create_index(op.f("ix_vehicle_makes_name"), "vehicle_makes", ["name"], unique=True)
    op.create_index(
        op.f("ix_vehicle_makes_normalized_name"), "vehicle_makes", ["normalized_name"], unique=True
    )
    op.create_table(
        "analytics_events",
        sa.Column("user_id", sa.String(length=36), nullable=True),
        sa.Column("anonymous_id", sa.String(length=100), nullable=True),
        sa.Column("event_name", sa.String(length=80), nullable=False),
        sa.Column("properties", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_analytics_events_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_analytics_events")),
    )
    op.create_index(
        op.f("ix_analytics_events_anonymous_id"), "analytics_events", ["anonymous_id"], unique=False
    )
    op.create_index(
        op.f("ix_analytics_events_event_name"), "analytics_events", ["event_name"], unique=False
    )
    op.create_index(
        op.f("ix_analytics_events_user_id"), "analytics_events", ["user_id"], unique=False
    )
    op.create_table(
        "region_profiles",
        sa.Column("country_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("city", sa.String(length=120), nullable=True),
        sa.Column("road_context", sa.JSON(), nullable=False),
        sa.Column("climate_context", sa.JSON(), nullable=False),
        sa.Column("service_context", sa.JSON(), nullable=False),
        sa.Column("is_demo", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["country_id"],
            ["country_profiles.id"],
            name=op.f("fk_region_profiles_country_id_country_profiles"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_region_profiles")),
        sa.UniqueConstraint("country_id", "name", name=op.f("uq_region_profiles_country_id")),
    )
    op.create_index(
        op.f("ix_region_profiles_country_id"), "region_profiles", ["country_id"], unique=False
    )
    op.create_table(
        "vehicle_models",
        sa.Column("make_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("normalized_name", sa.String(length=120), nullable=False),
        sa.Column("is_demo", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["make_id"], ["vehicle_makes.id"], name=op.f("fk_vehicle_models_make_id_vehicle_makes")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vehicle_models")),
        sa.UniqueConstraint("make_id", "normalized_name", name=op.f("uq_vehicle_models_make_id")),
    )
    op.create_index(op.f("ix_vehicle_models_make_id"), "vehicle_models", ["make_id"], unique=False)
    op.create_index(
        op.f("ix_vehicle_models_normalized_name"),
        "vehicle_models",
        ["normalized_name"],
        unique=False,
    )
    op.create_table(
        "vehicle_generations",
        sa.Column("model_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("code", sa.String(length=80), nullable=True),
        sa.Column("start_year", sa.Integer(), nullable=True),
        sa.Column("end_year", sa.Integer(), nullable=True),
        sa.Column("is_demo", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["model_id"],
            ["vehicle_models.id"],
            name=op.f("fk_vehicle_generations_model_id_vehicle_models"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vehicle_generations")),
        sa.UniqueConstraint(
            "model_id", "code", "start_year", name=op.f("uq_vehicle_generations_model_id")
        ),
    )
    op.create_index(
        op.f("ix_vehicle_generations_model_id"), "vehicle_generations", ["model_id"], unique=False
    )
    op.create_table(
        "vehicle_variants",
        sa.Column("generation_id", sa.String(length=36), nullable=False),
        sa.Column("specification_source_id", sa.String(length=36), nullable=True),
        sa.Column("market", sa.String(length=2), nullable=False),
        sa.Column("name", sa.String(length=180), nullable=False),
        sa.Column("year_from", sa.Integer(), nullable=True),
        sa.Column("year_to", sa.Integer(), nullable=True),
        sa.Column("engine_code", sa.String(length=80), nullable=True),
        sa.Column("engine", sa.String(length=160), nullable=True),
        sa.Column("transmission_code", sa.String(length=80), nullable=True),
        sa.Column("transmission", sa.String(length=120), nullable=True),
        sa.Column("drivetrain", sa.String(length=40), nullable=True),
        sa.Column("body", sa.String(length=60), nullable=True),
        sa.Column("fuel", sa.String(length=40), nullable=True),
        sa.Column("displacement_l", sa.Numeric(precision=4, scale=2), nullable=True),
        sa.Column("power_kw", sa.Numeric(precision=7, scale=2), nullable=True),
        sa.Column("ground_clearance_mm", sa.Integer(), nullable=True),
        sa.Column("official_fuel_city_l_100km", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("official_fuel_highway_l_100km", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("specifications", sa.JSON(), nullable=False),
        sa.Column("is_demo", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["generation_id"],
            ["vehicle_generations.id"],
            name=op.f("fk_vehicle_variants_generation_id_vehicle_generations"),
        ),
        sa.ForeignKeyConstraint(
            ["specification_source_id"],
            ["source_records.id"],
            name=op.f("fk_vehicle_variants_specification_source_id_source_records"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vehicle_variants")),
    )
    op.create_index(
        op.f("ix_vehicle_variants_generation_id"),
        "vehicle_variants",
        ["generation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_vehicle_variants_is_demo"), "vehicle_variants", ["is_demo"], unique=False
    )
    op.create_index(
        op.f("ix_vehicle_variants_market"), "vehicle_variants", ["market"], unique=False
    )
    op.create_index(
        op.f("ix_vehicle_variants_specification_source_id"),
        "vehicle_variants",
        ["specification_source_id"],
        unique=False,
    )
    op.create_table(
        "analysis_requests",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("vehicle_variant_id", sa.String(length=36), nullable=True),
        sa.Column("country", sa.String(length=2), nullable=False),
        sa.Column("city", sa.String(length=120), nullable=True),
        sa.Column("language", sa.String(length=5), nullable=False),
        sa.Column("vehicle_input", sa.JSON(), nullable=False),
        sa.Column("usage_profile", sa.JSON(), nullable=False),
        sa.Column("selected_price", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("mileage_km", sa.Integer(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_analysis_requests_user_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["vehicle_variant_id"],
            ["vehicle_variants.id"],
            name=op.f("fk_analysis_requests_vehicle_variant_id_vehicle_variants"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_analysis_requests")),
    )
    op.create_index(
        op.f("ix_analysis_requests_country"), "analysis_requests", ["country"], unique=False
    )
    op.create_index(
        op.f("ix_analysis_requests_user_id"), "analysis_requests", ["user_id"], unique=False
    )
    op.create_index(
        op.f("ix_analysis_requests_vehicle_variant_id"),
        "analysis_requests",
        ["vehicle_variant_id"],
        unique=False,
    )
    op.create_table(
        "known_issues",
        sa.Column("vehicle_variant_id", sa.String(length=36), nullable=False),
        sa.Column("component", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("affected_variants", sa.JSON(), nullable=False),
        sa.Column("conditions", sa.JSON(), nullable=False),
        sa.Column("typical_mileage_min", sa.Integer(), nullable=True),
        sa.Column("typical_mileage_max", sa.Integer(), nullable=True),
        sa.Column(
            "severity",
            sa.Enum("LOW", "MEDIUM", "HIGH", "CRITICAL", name="issue_severity", native_enum=False),
            nullable=False,
        ),
        sa.Column("evidence_ids", sa.JSON(), nullable=False),
        sa.Column(
            "confidence",
            sa.Enum("LOW", "MEDIUM", "HIGH", name="issue_confidence", native_enum=False),
            nullable=False,
        ),
        sa.Column("inspection_recommendation", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "CONFIRMED",
                "ESTIMATE",
                "NEEDS_INSPECTION",
                "INSUFFICIENT_DATA",
                name="known_issue_status",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("is_demo", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["vehicle_variant_id"],
            ["vehicle_variants.id"],
            name=op.f("fk_known_issues_vehicle_variant_id_vehicle_variants"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_known_issues")),
    )
    op.create_index(op.f("ix_known_issues_component"), "known_issues", ["component"], unique=False)
    op.create_index(op.f("ix_known_issues_is_demo"), "known_issues", ["is_demo"], unique=False)
    op.create_index(
        op.f("ix_known_issues_vehicle_variant_id"),
        "known_issues",
        ["vehicle_variant_id"],
        unique=False,
    )
    op.create_table(
        "local_cost_items",
        sa.Column("source_id", sa.String(length=36), nullable=False),
        sa.Column("country", sa.String(length=2), nullable=False),
        sa.Column("city", sa.String(length=120), nullable=True),
        sa.Column("vehicle_variant_id", sa.String(length=36), nullable=True),
        sa.Column("applicability", sa.JSON(), nullable=False),
        sa.Column("category", sa.String(length=100), nullable=False),
        sa.Column("operation", sa.String(length=200), nullable=False),
        sa.Column("part_price_low", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("part_price_high", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("labor_price_low", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("labor_price_high", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("updated_at_source", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_demo", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["source_records.id"],
            name=op.f("fk_local_cost_items_source_id_source_records"),
        ),
        sa.ForeignKeyConstraint(
            ["vehicle_variant_id"],
            ["vehicle_variants.id"],
            name=op.f("fk_local_cost_items_vehicle_variant_id_vehicle_variants"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_local_cost_items")),
    )
    op.create_index(
        op.f("ix_local_cost_items_category"), "local_cost_items", ["category"], unique=False
    )
    op.create_index(op.f("ix_local_cost_items_city"), "local_cost_items", ["city"], unique=False)
    op.create_index(
        op.f("ix_local_cost_items_country"), "local_cost_items", ["country"], unique=False
    )
    op.create_index(
        op.f("ix_local_cost_items_is_demo"), "local_cost_items", ["is_demo"], unique=False
    )
    op.create_index(
        op.f("ix_local_cost_items_source_id"), "local_cost_items", ["source_id"], unique=False
    )
    op.create_index(
        op.f("ix_local_cost_items_vehicle_variant_id"),
        "local_cost_items",
        ["vehicle_variant_id"],
        unique=False,
    )
    op.create_table(
        "market_listings",
        sa.Column("vehicle_variant_id", sa.String(length=36), nullable=True),
        sa.Column("source_id", sa.String(length=36), nullable=False),
        sa.Column("external_key", sa.String(length=200), nullable=False),
        sa.Column("country", sa.String(length=2), nullable=False),
        sa.Column("city", sa.String(length=120), nullable=True),
        sa.Column("make", sa.String(length=120), nullable=False),
        sa.Column("model", sa.String(length=120), nullable=False),
        sa.Column("generation", sa.String(length=120), nullable=True),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("engine", sa.String(length=160), nullable=True),
        sa.Column("displacement_l", sa.Numeric(precision=4, scale=2), nullable=True),
        sa.Column("transmission", sa.String(length=120), nullable=True),
        sa.Column("drivetrain", sa.String(length=40), nullable=True),
        sa.Column("mileage_km", sa.Integer(), nullable=True),
        sa.Column("price", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_demo", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["source_records.id"],
            name=op.f("fk_market_listings_source_id_source_records"),
        ),
        sa.ForeignKeyConstraint(
            ["vehicle_variant_id"],
            ["vehicle_variants.id"],
            name=op.f("fk_market_listings_vehicle_variant_id_vehicle_variants"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_market_listings")),
        sa.UniqueConstraint("source_id", "external_key", name=op.f("uq_market_listings_source_id")),
    )
    op.create_index(op.f("ix_market_listings_city"), "market_listings", ["city"], unique=False)
    op.create_index(
        op.f("ix_market_listings_country"), "market_listings", ["country"], unique=False
    )
    op.create_index(
        op.f("ix_market_listings_is_demo"), "market_listings", ["is_demo"], unique=False
    )
    op.create_index(op.f("ix_market_listings_make"), "market_listings", ["make"], unique=False)
    op.create_index(op.f("ix_market_listings_model"), "market_listings", ["model"], unique=False)
    op.create_index(
        op.f("ix_market_listings_observed_at"), "market_listings", ["observed_at"], unique=False
    )
    op.create_index(
        op.f("ix_market_listings_source_id"), "market_listings", ["source_id"], unique=False
    )
    op.create_index(
        op.f("ix_market_listings_vehicle_variant_id"),
        "market_listings",
        ["vehicle_variant_id"],
        unique=False,
    )
    op.create_table(
        "owner_evidence",
        sa.Column("source_id", sa.String(length=36), nullable=False),
        sa.Column("vehicle_variant_id", sa.String(length=36), nullable=False),
        sa.Column("owner_identity_key", sa.String(length=200), nullable=True),
        sa.Column("material_identity_key", sa.String(length=200), nullable=False),
        sa.Column("dedupe_key", sa.String(length=64), nullable=False),
        sa.Column("mileage_km", sa.Integer(), nullable=True),
        sa.Column("component", sa.String(length=100), nullable=False),
        sa.Column("topic", sa.String(length=120), nullable=False),
        sa.Column(
            "sentiment",
            sa.Enum(
                "POSITIVE",
                "NEGATIVE",
                "MIXED",
                "NEUTRAL",
                name="owner_sentiment",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("issue_type", sa.String(length=120), nullable=True),
        sa.Column("excerpt", sa.Text(), nullable=True),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_demo", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["source_records.id"],
            name=op.f("fk_owner_evidence_source_id_source_records"),
        ),
        sa.ForeignKeyConstraint(
            ["vehicle_variant_id"],
            ["vehicle_variants.id"],
            name=op.f("fk_owner_evidence_vehicle_variant_id_vehicle_variants"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_owner_evidence")),
        sa.UniqueConstraint(
            "vehicle_variant_id", "dedupe_key", name=op.f("uq_owner_evidence_vehicle_variant_id")
        ),
    )
    op.create_index(
        op.f("ix_owner_evidence_component"), "owner_evidence", ["component"], unique=False
    )
    op.create_index(
        op.f("ix_owner_evidence_dedupe_key"), "owner_evidence", ["dedupe_key"], unique=False
    )
    op.create_index(op.f("ix_owner_evidence_is_demo"), "owner_evidence", ["is_demo"], unique=False)
    op.create_index(
        op.f("ix_owner_evidence_material_identity_key"),
        "owner_evidence",
        ["material_identity_key"],
        unique=False,
    )
    op.create_index(
        op.f("ix_owner_evidence_source_id"), "owner_evidence", ["source_id"], unique=False
    )
    op.create_index(op.f("ix_owner_evidence_topic"), "owner_evidence", ["topic"], unique=False)
    op.create_index(
        op.f("ix_owner_evidence_vehicle_variant_id"),
        "owner_evidence",
        ["vehicle_variant_id"],
        unique=False,
    )
    op.create_table(
        "technical_evidence",
        sa.Column("vehicle_variant_id", sa.String(length=36), nullable=False),
        sa.Column("source_id", sa.String(length=36), nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "ENGINE",
                "TRANSMISSION",
                "SUSPENSION",
                "STEERING",
                "BRAKES",
                "ELECTRICAL",
                "BODY",
                "MAINTENANCE",
                "FUEL",
                "SAFETY",
                "OTHER",
                name="evidence_category",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=240), nullable=False),
        sa.Column("statement", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "CONFIRMED",
                "ESTIMATE",
                "NEEDS_INSPECTION",
                "INSUFFICIENT_DATA",
                name="evidence_status",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "confidence",
            sa.Enum("LOW", "MEDIUM", "HIGH", name="evidence_confidence", native_enum=False),
            nullable=False,
        ),
        sa.Column("market", sa.String(length=2), nullable=True),
        sa.Column("conditions", sa.JSON(), nullable=False),
        sa.Column("is_demo", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["source_records.id"],
            name=op.f("fk_technical_evidence_source_id_source_records"),
        ),
        sa.ForeignKeyConstraint(
            ["vehicle_variant_id"],
            ["vehicle_variants.id"],
            name=op.f("fk_technical_evidence_vehicle_variant_id_vehicle_variants"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_technical_evidence")),
    )
    op.create_index(
        op.f("ix_technical_evidence_category"), "technical_evidence", ["category"], unique=False
    )
    op.create_index(
        op.f("ix_technical_evidence_is_demo"), "technical_evidence", ["is_demo"], unique=False
    )
    op.create_index(
        op.f("ix_technical_evidence_source_id"), "technical_evidence", ["source_id"], unique=False
    )
    op.create_index(
        op.f("ix_technical_evidence_status"), "technical_evidence", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_technical_evidence_vehicle_variant_id"),
        "technical_evidence",
        ["vehicle_variant_id"],
        unique=False,
    )
    op.create_table(
        "reports",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("analysis_request_id", sa.String(length=36), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PREVIEW", "FULL", "FAILED", name="report_status", native_enum=False),
            nullable=False,
        ),
        sa.Column("language", sa.String(length=5), nullable=False),
        sa.Column("report_version", sa.String(length=30), nullable=False),
        sa.Column("is_unlocked", sa.Boolean(), nullable=False),
        sa.Column("is_demo", sa.Boolean(), nullable=False),
        sa.Column("input_snapshot", sa.JSON(), nullable=False),
        sa.Column("evidence_bundle", sa.JSON(), nullable=False),
        sa.Column("calculated_data", sa.JSON(), nullable=False),
        sa.Column("generated_sections", sa.JSON(), nullable=False),
        sa.Column("methodology_version", sa.String(length=30), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["analysis_request_id"],
            ["analysis_requests.id"],
            name=op.f("fk_reports_analysis_request_id_analysis_requests"),
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_reports_user_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reports")),
    )
    op.create_index(
        op.f("ix_reports_analysis_request_id"), "reports", ["analysis_request_id"], unique=False
    )
    op.create_index(op.f("ix_reports_is_demo"), "reports", ["is_demo"], unique=False)
    op.create_index(op.f("ix_reports_is_unlocked"), "reports", ["is_unlocked"], unique=False)
    op.create_index(op.f("ix_reports_user_id"), "reports", ["user_id"], unique=False)
    op.create_table(
        "payments",
        sa.Column("report_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("provider", sa.String(length=80), nullable=False),
        sa.Column("external_payment_id", sa.String(length=200), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "SUCCEEDED",
                "FAILED",
                "REFUNDED",
                "ADMIN_UNLOCKED",
                name="payment_status",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("provider_payload", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["report_id"], ["reports.id"], name=op.f("fk_payments_report_id_reports")
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_payments_user_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payments")),
    )
    op.create_index(
        op.f("ix_payments_external_payment_id"), "payments", ["external_payment_id"], unique=False
    )
    op.create_index(op.f("ix_payments_report_id"), "payments", ["report_id"], unique=False)
    op.create_index(op.f("ix_payments_user_id"), "payments", ["user_id"], unique=False)
    op.create_table(
        "report_questions",
        sa.Column("report_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("question", sa.Text(), nullable=False),
        sa.Column("answer", sa.Text(), nullable=True),
        sa.Column("evidence_snapshot", sa.JSON(), nullable=False),
        sa.Column("succeeded", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["report_id"], ["reports.id"], name=op.f("fk_report_questions_report_id_reports")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_report_questions_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_report_questions")),
    )
    op.create_index(
        op.f("ix_report_questions_report_id"), "report_questions", ["report_id"], unique=False
    )
    op.create_index(
        op.f("ix_report_questions_user_id"), "report_questions", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_report_questions_user_id"), table_name="report_questions")
    op.drop_index(op.f("ix_report_questions_report_id"), table_name="report_questions")
    op.drop_table("report_questions")
    op.drop_index(op.f("ix_payments_user_id"), table_name="payments")
    op.drop_index(op.f("ix_payments_report_id"), table_name="payments")
    op.drop_index(op.f("ix_payments_external_payment_id"), table_name="payments")
    op.drop_table("payments")
    op.drop_index(op.f("ix_reports_user_id"), table_name="reports")
    op.drop_index(op.f("ix_reports_is_unlocked"), table_name="reports")
    op.drop_index(op.f("ix_reports_is_demo"), table_name="reports")
    op.drop_index(op.f("ix_reports_analysis_request_id"), table_name="reports")
    op.drop_table("reports")
    op.drop_index(op.f("ix_technical_evidence_vehicle_variant_id"), table_name="technical_evidence")
    op.drop_index(op.f("ix_technical_evidence_status"), table_name="technical_evidence")
    op.drop_index(op.f("ix_technical_evidence_source_id"), table_name="technical_evidence")
    op.drop_index(op.f("ix_technical_evidence_is_demo"), table_name="technical_evidence")
    op.drop_index(op.f("ix_technical_evidence_category"), table_name="technical_evidence")
    op.drop_table("technical_evidence")
    op.drop_index(op.f("ix_owner_evidence_vehicle_variant_id"), table_name="owner_evidence")
    op.drop_index(op.f("ix_owner_evidence_topic"), table_name="owner_evidence")
    op.drop_index(op.f("ix_owner_evidence_source_id"), table_name="owner_evidence")
    op.drop_index(op.f("ix_owner_evidence_material_identity_key"), table_name="owner_evidence")
    op.drop_index(op.f("ix_owner_evidence_is_demo"), table_name="owner_evidence")
    op.drop_index(op.f("ix_owner_evidence_dedupe_key"), table_name="owner_evidence")
    op.drop_index(op.f("ix_owner_evidence_component"), table_name="owner_evidence")
    op.drop_table("owner_evidence")
    op.drop_index(op.f("ix_market_listings_vehicle_variant_id"), table_name="market_listings")
    op.drop_index(op.f("ix_market_listings_source_id"), table_name="market_listings")
    op.drop_index(op.f("ix_market_listings_observed_at"), table_name="market_listings")
    op.drop_index(op.f("ix_market_listings_model"), table_name="market_listings")
    op.drop_index(op.f("ix_market_listings_make"), table_name="market_listings")
    op.drop_index(op.f("ix_market_listings_is_demo"), table_name="market_listings")
    op.drop_index(op.f("ix_market_listings_country"), table_name="market_listings")
    op.drop_index(op.f("ix_market_listings_city"), table_name="market_listings")
    op.drop_table("market_listings")
    op.drop_index(op.f("ix_local_cost_items_vehicle_variant_id"), table_name="local_cost_items")
    op.drop_index(op.f("ix_local_cost_items_source_id"), table_name="local_cost_items")
    op.drop_index(op.f("ix_local_cost_items_is_demo"), table_name="local_cost_items")
    op.drop_index(op.f("ix_local_cost_items_country"), table_name="local_cost_items")
    op.drop_index(op.f("ix_local_cost_items_city"), table_name="local_cost_items")
    op.drop_index(op.f("ix_local_cost_items_category"), table_name="local_cost_items")
    op.drop_table("local_cost_items")
    op.drop_index(op.f("ix_known_issues_vehicle_variant_id"), table_name="known_issues")
    op.drop_index(op.f("ix_known_issues_is_demo"), table_name="known_issues")
    op.drop_index(op.f("ix_known_issues_component"), table_name="known_issues")
    op.drop_table("known_issues")
    op.drop_index(op.f("ix_analysis_requests_vehicle_variant_id"), table_name="analysis_requests")
    op.drop_index(op.f("ix_analysis_requests_user_id"), table_name="analysis_requests")
    op.drop_index(op.f("ix_analysis_requests_country"), table_name="analysis_requests")
    op.drop_table("analysis_requests")
    op.drop_index(
        op.f("ix_vehicle_variants_specification_source_id"), table_name="vehicle_variants"
    )
    op.drop_index(op.f("ix_vehicle_variants_market"), table_name="vehicle_variants")
    op.drop_index(op.f("ix_vehicle_variants_is_demo"), table_name="vehicle_variants")
    op.drop_index(op.f("ix_vehicle_variants_generation_id"), table_name="vehicle_variants")
    op.drop_table("vehicle_variants")
    op.drop_index(op.f("ix_vehicle_generations_model_id"), table_name="vehicle_generations")
    op.drop_table("vehicle_generations")
    op.drop_index(op.f("ix_vehicle_models_normalized_name"), table_name="vehicle_models")
    op.drop_index(op.f("ix_vehicle_models_make_id"), table_name="vehicle_models")
    op.drop_table("vehicle_models")
    op.drop_index(op.f("ix_region_profiles_country_id"), table_name="region_profiles")
    op.drop_table("region_profiles")
    op.drop_index(op.f("ix_analytics_events_user_id"), table_name="analytics_events")
    op.drop_index(op.f("ix_analytics_events_event_name"), table_name="analytics_events")
    op.drop_index(op.f("ix_analytics_events_anonymous_id"), table_name="analytics_events")
    op.drop_table("analytics_events")
    op.drop_index(op.f("ix_vehicle_makes_normalized_name"), table_name="vehicle_makes")
    op.drop_index(op.f("ix_vehicle_makes_name"), table_name="vehicle_makes")
    op.drop_table("vehicle_makes")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_source_records_source_type"), table_name="source_records")
    op.drop_index(op.f("ix_source_records_market"), table_name="source_records")
    op.drop_index(op.f("ix_source_records_is_demo"), table_name="source_records")
    op.drop_table("source_records")
    op.drop_index(op.f("ix_country_profiles_country_code"), table_name="country_profiles")
    op.drop_table("country_profiles")
    # ### end Alembic commands ###
