// English of the web texts, keyed by the Russian text (product phase, stage 1).
// pickText(language, ru, az, en): AZ, EN (given, else from the table), RU otherwise.
export const EN = {
"Русский": "Russian",
"Версии приложения и сервиса не совпадают": "App and service versions do not match",
"Для этого приложения нужен локальный сервис 0.8.1. Запустите согласованную сборку.": "This app requires local service 0.8.1. Run a matching build.",
"VIN · 17 символов": "VIN · 17 characters",
"Профиль": "Profile",
"Настройки тестирования": "Test settings",
"Сравнение": "Compare",
"Проверить": "Check",
"Включён режим обычного пользователя. Локальный полный доступ доступен владельцу при выключенном Simulate User Paywall; покупка данных не выполнялась.": "Regular user mode is on. Full local access is available to the owner when Simulate User Paywall is off; no data was purchased.",
"Двигатель внутреннего сгорания": "Internal combustion engine",
"США": "USA",
"Выберите рынок": "Choose a market",
"Бесступенчатая, ручной режим": "CVT with manual shift mode",
"Механическая": "Manual",
"Редуктор": "Reduction gear",
"Передний привод": "Front-wheel drive",
"Задний привод": "Rear-wheel drive",
"Полный привод": "All-wheel drive",
"Получаем доступные сведения из источников. Это может занять несколько минут.": "Retrieving available source data. This may take a few minutes.",
"На главную": "Home",
"Фото объявления": "Listing photo",
"Фото объявления · продавец": "Listing photo · seller",
"Разберитесь в автомобиле до покупки": "Understand a car before you buy",
"Узнать об автомобиле": "Explore a car",
"VIN необязателен. Начните с автомобиля, который вам интересен.": "VIN is optional. Start with the car you are considering.",
"Какой автомобиль вас интересует?": "Which car are you considering?",
"Версия для разбора сохранённого объявления": "Configuration for the saved listing",
"Заполнить параметры": "Enter details",
"Марка": "Make",
"Модель": "Model",
"Год": "Year",
"Не знаю": "Not sure",
"Рынок продажи новой машины отличается от страны сборки и страны ваших поездок.": "The market where the car was first sold new may differ from where it was built and where you drive.",
"Топливо": "Fuel",
"Продолжить": "Continue",
"Выбранный автомобиль": "Selected vehicle",
"Характеристики выбранной версии": "Selected configuration specs",
"Рынок": "Market",
"Изменить": "Edit",
"Сейчас автоматический каталог модификаций доступен для США. Можно выбрать американскую версию для справочного сравнения. Это не подтверждает исходный рынок вашего автомобиля.": "Automatic configuration lookup currently covers the USA. You can select a US configuration as a reference for comparison. This does not confirm your car’s original market.",
"Выбрать версию США как справочную": "Use a US configuration as reference",
"Получить разбор": "Get analysis",
"Объявление или VIN": "Listing or VIN",
"Другой рынок / номер кузова": "Other market / frame number",
"Номер кузова": "Frame number",
"Номер шасси": "Chassis number",
"Объявление получено": "Listing received",
"Сведения продавца. VIN не требуется для разбора.": "Seller-supplied information. VIN is not required for analysis.",
"Разобрать предложение": "Analyze this offer",
"Уточнить данные": "Refine details",
"Ссылка сохранена": "Link saved",
"Описание объявления": "Listing description",
"Сохранить описание и продолжить": "Save description and continue",
"Продолжить по параметрам": "Continue with vehicle details",
"Источник ограничивает автоматический доступ.": "The source restricts automated access.",
"Ссылка ведёт на служебный или локальный адрес. Загрузка запрещена.": "The link points to an internal or local address. Loading is blocked.",
"Автоматическое извлечение не выполнено.": "Automatic extraction failed.",
"Подбираем версию и изучаем источники": "Matching the configuration and researching sources",
"Уточните модификацию": "Choose the configuration",
"Выбрать эту конфигурацию": "Choose this configuration",
"Изменить параметры": "Edit details",
"Версия пока не определена": "Configuration not determined yet",
"Уточнить": "Refine",
"Готовим досье из найденных данных": "Preparing the dossier from retrieved data",
"Источники и применимость": "Sources and applicability",
"Подтверждённых подробностей пока нет в подключённых источниках.": "Connected sources have no confirmed details yet.",
"Источники раздела": "Section sources",
"Спросить Auto Expert": "Ask Auto Expert",
"Добавить к сравнению": "Add to comparison",
"Дополнить VIN-историей": "Add VIN history",
"Сохранённый отчёт. Новое исследование создаёт отдельный снимок.": "Saved report. New research creates a separate snapshot.",
"Сравнить автомобили": "Compare vehicles",
"Два варианта достаточно. Третий — по желанию.": "Two options are enough. A third is optional.",
"Убрать / заменить": "Remove / replace",
"Добавить вариант": "Add an option",
"По параметрам": "By vehicle details",
"Ссылка или VIN": "Link or VIN",
"Что для вас важно?": "What matters to you?",
"Пробег в месяц, км": "Monthly mileage, km",
"Город эксплуатации": "City where you drive",
"Дороги и маршруты": "Roads and trips",
"Сравнить выбранные": "Compare selected",
"Модель без VIN": "Model without VIN",
"Объявление": "Listing",
"Мои отчёты": "My reports",
"Открыть": "Open",
"Здесь появятся ваши разборы и сравнения.": "Your analyses and comparisons will appear here.",
"Ранее сохранённые VIN-отчёты": "Previously saved VIN reports",
"Ответы по источникам отчёта. В этой локальной версии используется ограниченный алгоритм, а не свободная беседа с языковой моделью.": "Answers are based on the report's sources. This local version uses a limited algorithm, not an open-ended conversation with a language model.",
"Какой бензин нужен?": "What fuel grade does it need?",
"Вопрос": "Question",
"Спросить по этому отчёту": "Ask about this report",
"Отправить": "Send",
"Вернуться к отчёту": "Back to report",
"PDF передан для сохранения": "PDF sent for saving",
"Укажите марку, модель и год": "Enter make, model and year",
"В сравнении уже три варианта": "The comparison already has three options",
"Добавлено к сравнению": "Added to comparison",
"Получаем объявление": "Retrieving listing",
"Сопоставляем выбранные автомобили": "Comparing selected vehicles",
"Импорт ТО, деталей и цен": "Import maintenance, parts and prices",
"Скачать схемы и заголовок CSV": "Download schemas and CSV header",
"Публикация AZ/RU · JSON": "AZ/RU publication · JSON",
"ID публикации": "Publication ID",
"Опубликовать проверенный материал": "Publish reviewed content",
"Коммерческие права не подтверждены": "Commercial rights not confirmed",
"Твой честный автоэксперт без предвзятости": "Your honest, unbiased car expert",
"Двигатель": "Engine",
"Коробка": "Transmission",
"Кузов": "Body",
"Исходный рынок": "Original market",
"Уже есть 2–3 варианта": "I already have 2–3 options",
"Найдите версии в каталоге и сравните их": "Find configurations in the catalog and compare them",
"Ваши предпочтения": "Your preferences",
"Не важно": "No preference",
"Да": "Yes",
"Нет": "No",
"Включить первое обслуживание в бюджет": "Include first service in the budget",
"Необязательно": "Optional",
"Поиск марки или модели": "Search make or model",
"Рынок первой продажи отличается от страны сборки. Официальный дилер — это канал поставки.": "The first-sale market can differ from the country of assembly. An authorized dealer is a supply channel.",
"Клиренс от, мм": "Min. ground clearance, mm",
"Объём до, л": "Max. displacement, L",
"Нужен большой багажник (от 450 л)": "Large cargo area needed (450 L or more)",
"Назад": "Back",
"Показать подходящие машины": "Show matching cars",
"Срок владения, месяцев": "Ownership period, months",
"Есть регулярная зарядка?": "Do you have regular access to charging?",
"Город": "City",
"Трасса": "Highway",
"Неровные дороги": "Rough roads",
"Семейное использование": "Family use",
"Что важнее? Выберите до трёх": "What matters most? Choose up to three",
"Динамика": "Performance",
"Подтверждённые совпадения": "Confirmed matches",
"Нужно уточнить": "Needs clarification",
"моделей": "models",
"версий": "configurations",
"Сортировка": "Sort",
"По совпадению условий": "Best match",
"По расходу, отдельно по циклу и энергии": "By fuel economy (per cycle and energy type)",
"Попробуйте изменить один из параметров": "Try changing one of the filters",
"Измените один параметр и повторите подбор.": "Change one filter and search again.",
"Число мест": "Number of seats",
"Проверьте параметр": "Check this filter",
"Открыть профиль": "Open profile",
"В сравнение": "Add to compare",
"Выбрано": "Selected",
"Сравнить выбранные машины": "Compare selected cars",
"Убрать": "Remove",
"Рынок США · только подтверждённые сочетания и годы": "US market · confirmed combinations and years only",
"Не подтверждено": "Not confirmed",
"Цена в AZ по свежим объявлениям": "AZ price from recent listings",
"Проверить объявление или VIN": "Check a listing or VIN",
"Главные различия": "Key differences",
"Расходы за 24 месяца": "Costs over 24 months",
"Сценарий расходов": "Cost scenario",
"Обслуживание за период, AZN": "Maintenance for the period, AZN",
"Резерв ремонта за период, AZN": "Repair reserve for the period, AZN",
"Прочие расходы, AZN": "Other costs, AZN",
"Дата цен": "Price date",
"Источник цен или ваше допущение": "Price source or your assumption",
"Полная стоимость пока неизвестна": "Total cost not known yet",
"Известная часть": "Known portion",
"Потеря стоимости": "Depreciation",
"Энергия": "Energy",
"Обслуживание": "Maintenance",
"Страна регистрации": "Country of registration",
"Для выбранной страны поиск по госномеру сейчас недоступен. Продолжите по VIN, ссылке на объявление или данным автомобиля.": "License plate lookup is not available for the selected country yet. Continue with a VIN, a listing link or vehicle details.",
"Ввести данные автомобиля": "Enter vehicle details",
"VIN / ссылка на объявление": "VIN / listing link",
"Пары пока не найдены в каталоге": "No comparison pairs in the catalog yet",
"Составьте своё сравнение из доступных версий.": "Build your own comparison from the available configurations.",
"Ограничения": "Limitations",
"Сравнить под мои условия": "Compare for my conditions",
"Подбор и базовый каталог доступны без входа. Войдите, чтобы сохранять отчёты.": "Search and the basic catalog are available without signing in. Sign in to save reports.",
"Войти": "Sign in",
"Создать аккаунт": "Create account",
"Выйти": "Sign out",
"Редакторский кабинет": "Editor dashboard",
"Загружаем опубликованные данные…": "Loading published data…",
"Манифест JSON": "JSON manifest",
"Поставить в очередь": "Add to queue",
"Основание решения": "Reason for decision",
"Отменить": "Cancel",
"Данные и ошибки": "Data and errors",
"Приостановить": "Pause",
"Загрузить документ": "Upload document",
"ID документа": "Document ID",
"США · модельные годы с 2012-го · 75 моделей продуктового каталога.": "USA · model years 2012 and later · 75 models in the product catalog.",
"Открыть разбор": "Open analysis",
"Лучше соответствует вашему запросу": "Best match for your request",
"Другие подходящие модели": "Other matching models",
"Пока недостаточно данных для оценки": "Not enough data to rate yet",
"Подтверждение относится только к указанным годам, рынку и сочетанию агрегатов. VIN, комплектация и состояние конкретного автомобиля требуют отдельной проверки.": "Confirmation applies only to the listed years, market and powertrain combination. The VIN, trim and condition of a specific vehicle need a separate check.",
"Цена предложения": "Asking price",
"Документ или ссылка с условиями использования": "Document or link with terms of use",
"Коммерческое использование разрешено документом": "Commercial use permitted by the document",
"мес.": "mo.",
"ID версии из каталога": "Catalog configuration ID",
"Отправить исправление на проверку": "Submit correction for review",
"Снять защиту обновления": "Remove update lock",
"Обычный текст": "Normal text",
"Похожие названия · выберите сами": "Similar names · pick one",
"Рекомендация учитывает условия запроса и подтверждённые измеримые предпочтения. Причины показаны в первой карточке; неизвестные надёжность, цены и расходы не получают выдуманной оценки.": "The recommendation considers your request and confirmed measurable preferences. Reasons are shown on the first card; unknown reliability, prices and costs do not get made-up scores.",
"Бензин": "Gasoline",
"л": "L",
"турбо": "turbo",
"механический нагнетатель": "supercharger",
"трансмиссия e-CVT": "e-CVT transmission",
"бесступенчатая трансмиссия": "continuously variable transmission",
"робот с двойным сцеплением": "dual-clutch transmission",
"одноступенчатый редуктор": "single-speed reduction gear",
"классический автомат": "conventional automatic",
"механическая коробка": "manual transmission",
"автомат, тип не уточнён": "automatic, type not specified",
"Электропривод": "Electric drive",
"Турбо": "Turbo",
"Без наддува": "Naturally aspirated",
"Механический нагнетатель": "Supercharger",
"У меня уже есть варианты": "I already have options",
"Ручной ввод": "Manual entry",
"Моторное масло": "Engine oil",
"Вязкость": "Viscosity",
"Допуск / спецификация": "Approval / specification",
"Объём с фильтром": "Capacity with filter",
"Раздатка": "Transfer case",
"Охлаждающая жидкость": "Coolant",
"Тормозная жидкость": "Brake fluid",
"Проверить конкретную машину": "Check a specific vehicle",
"Проверка": "Check",
"Начните с VIN, объявления или известных вам параметров.": "Start with a VIN, a listing or the details you know.",
"Ссылка Turbo.az": "Turbo.az link",
"Ввести вручную": "Enter manually",
"Проверка по VIN": "VIN check",
"Состав проверки зависит от предварительного ответа источника.": "What the check includes depends on the source's preliminary response.",
"Для тестового VIN доступен демонстрационный отчёт.": "A demo report is available for the test VIN.",
"VIN автомобиля": "Vehicle VIN",
"Проверить VIN": "Check VIN",
"Подставить тестовый VIN": "Insert test VIN",
"VIN из 17 символов": "17-character VIN",
"Одно объявление Turbo.az": "Single Turbo.az listing",
"Ссылка сохраняется как источник и автоматически не загружается. Для сопоставления вставьте текст объявления, сохранённую HTML-страницу или заполните поля вручную. Массовый сбор и подключение к Turbo.az выключены.": "The link is saved as a source and is not loaded automatically. To match it, paste the listing text, upload a saved HTML page or fill in the fields manually. Bulk collection and the Turbo.az connection are turned off.",
"Ссылка на объявление": "Listing URL",
"Текст объявления": "Listing text",
"Вставьте описание и основные параметры из объявления. Данные продавца будут показаны отдельно от проверенных характеристик.": "Paste the description and key details from the listing. Seller information is shown separately from verified specifications.",
"Сохранённая HTML-страница": "Saved HTML page",
"Можно загрузить один HTML-файл, который вы сохранили или вправе передать.": "You can upload one HTML file that you saved or are allowed to share.",
"Импортировать объявление": "Import listing",
"Основные параметры": "Key details",
"Укажите то, что известно. Пустые поля не будут добавлены в профиль.": "Enter what you know. Empty fields are not added to the profile.",
"Номер объявления": "Listing ID",
"Двигатель / объём": "Engine / displacement",
"Коробка, как указано продавцом": "Transmission as stated by seller",
"Привод": "Drivetrain",
"Заявленный рынок происхождения": "Stated market of origin",
"Цена": "Price",
"Валюта": "Currency",
"Пробег": "Mileage",
"Единица пробега": "Mileage unit",
"Цвет": "Color",
"Количество владельцев": "Number of owners",
"Состояние": "Condition",
"Тип продавца": "Seller type",
"Описание продавца": "Seller description",
"Сопоставить с каталогом": "Match to catalog",
"Профиль объявления": "Listing profile",
"Turbo.az · объявление": "Turbo.az · listing",
"Данные пользователя": "User-provided data",
"Открыть оригинал": "Open original",
"Указано в объявлении": "Stated in listing",
"Сопоставление Auto Expert": "Auto Expert match",
"Это сведения из объявления. Характеристики автомобиля подтверждаются отдельно.": "This information comes from the listing. Vehicle specifications are confirmed separately.",
"Найдена соответствующая версия в каталоге Auto Expert": "Matching configuration found in the Auto Expert catalog",
"Подходят несколько версий": "Several configurations match",
"Параметры объявления и каталога расходятся": "Listing and catalog details don't match",
"Проверить автомобиль по VIN": "Check vehicle by VIN",
"Можно продолжить проверку по VIN или уточнить параметры объявления.": "You can continue with a VIN check or refine the listing details.",
"В объявлении указано": "Listing states",
"Для выбранного года в каталоге Auto Expert подтверждено": "Confirmed in the Auto Expert catalog for the selected year",
"Перед покупкой проверьте VIN или документы автомобиля.": "Before you buy, check the VIN or the vehicle's documents.",
"Что уточнить": "What to clarify",
"Выбрать модель вручную": "Choose model manually",
"Добавить сведения": "Add details",
"Проверить историю по VIN": "Check VIN history",
"Добавить VIN и проверить историю": "Add VIN and check history",
"Автоматической загрузки по ссылке нет. Для сопоставления вставьте текст объявления, загрузите сохранённую страницу или заполните основные поля.": "Links are not loaded automatically. To match a listing, paste its text, upload a saved page or fill in the key fields.",
"Сопоставить объявление": "Match listing",
"Укажите прямую ссылку https://turbo.az на одно объявление.": "Enter a direct https://turbo.az link to a single listing.",
"Файл превышает допустимый размер 256 КБ.": "The file exceeds the 256 KB size limit.",
"Текст объявления превышает 60 КБ.": "Listing text exceeds 60 KB.",
"Выберите файл .html или .htm.": "Choose an .html or .htm file.",
"Сопоставляем объявление…": "Matching listing…",
"Не удалось обработать объявление. Проверьте ссылку или заполненные поля.": "Couldn't process the listing. Check the link or the fields you filled in.",
"Сравнение машин": "Vehicle comparison",
"В сравнении может быть до трёх машин.": "You can compare up to three vehicles.",
"Сравнить эту версию": "Compare this configuration",
" л": " L",
"Топливо / электричество": "Fuel / electricity",
"Рассчитанная часть эксплуатации": "Calculated share of operating costs",
"Полная эксплуатация": "Total operating costs",
"Цена покупки отдельно": "Purchase price separate",
"Покупка − перепродажа · сценарий": "Purchase − resale · scenario",
"Полная стоимость владения": "Total cost of ownership",
"Применимый регламент ТО ещё не исследован.": "The applicable maintenance schedule has not been researched yet.",
"Не хватает подтверждённых данных.": "Not enough confirmed data.",
"Стоимость владения · источники AZ": "Cost of ownership · AZ sources",
"Начало расчёта": "Calculation start",
"Текущий пробег, км": "Current mileage, km",
"Не указана": "Not specified",
"АИ-92": "AI-92",
"АИ-95": "AI-95",
"АИ-98": "AI-98",
"Дизель": "Diesel",
"Первая регистрация · если известна": "First registration · if known",
"Условия обслуживания": "Service conditions",
"Режим обслуживания": "Maintenance schedule",
"Обычный": "Normal",
"Тяжёлые условия по руководству": "Severe service per owner's manual",
"Сценарий первоначального ТО при неизвестной истории": "Initial service scenario when history is unknown",
"Доля домашней зарядки, 0–1": "Home charging share, 0–1",
"Не уточнена": "Not specified",
"От сети · потери включены": "From the grid · losses included",
"Новый отдельный счётчик для автомобиля": "New dedicated meter for the vehicle",
"Покупка и другие предположения": "Purchase and other assumptions",
"Цена покупки, AZN": "Purchase price, AZN",
"Предполагаемая перепродажа, AZN": "Estimated resale value, AZN",
"Резерв отдельно, AZN": "Reserve (separate), AZN",
"Другие учтённые расходы, AZN": "Other included costs, AZN",
"Будущий пробег распределён равномерно; последняя известная цена сохраняется как предположение. Отсутствующие ТО, детали и работа не равны нулю.": "Future mileage is spread evenly; the last known price is kept as an assumption. Missing maintenance, parts and labor are not counted as zero.",
"Рассчитать по источникам": "Calculate from sources",
"История ТО и предложения": "Service history and recommendations",
"Дата последней операции": "Date last performed",
"Одометр при операции, км": "Odometer at service, km",
"Подтверждаю: ещё не выполнялась": "I confirm: not performed yet",
"Применимый регламент ещё не опубликован. История не считается нулевой.": "The applicable schedule has not been published yet. History is not treated as empty.",
"Сведения о ТО временно недоступны.": "Maintenance information is temporarily unavailable.",
"Расчёт по заданным предположениям": "Calculation based on your assumptions",
"Что ещё не учтено": "Not included yet",
"По месяцам": "By month",
"Количество и тариф": "Quantity and rate",
"ступени": "tiers",
"Календарь ТО": "Maintenance calendar",
"Подтверждённого календаря пока нет.": "No confirmed schedule yet.",
"Расчёт…": "Calculating…",
"Скачать расчёт и источники · JSON": "Download calculation and sources · JSON",
"Сохранить в мои отчёты": "Save to My reports",
"Проверьте введённые значения и доступность локального сервера.": "Check the values you entered and that the local server is available.",
"Технические данные · США": "Specifications · USA",
"Техника": "Specs",
"Слабые места": "Known issues",
"Сервисные кампании": "Service campaigns",
"ТО": "Maintenance",
"Источники": "Sources",
"Узел": "Component",
"Серьёзность": "Severity",
"Вероятность": "Likelihood",
"Симптомы": "Symptoms",
"Как проверить": "How to check",
"Годы": "Years",
"Обычные условия": "Normal conditions",
"Тяжёлые условия": "Severe conditions",
"не позже": "no later than",
"стр.": "p.",
"Конфигурации технической базы США": "US technical database configurations",
"Предпросмотр за флагом: конфигурации исследовательского слоя не публикуются.": "Flagged preview: research-layer configurations are not published.",
"Модельный год": "Model year",
"Выберите": "Select",
"Конфигураций нет": "No configurations",
"Загрузка…": "Loading…",
"Технические данные для этой конфигурации не найдены.": "No technical data found for this configuration.",
"Подтверждены записи о повреждениях": "Damage records confirmed",
"Подтверждены записи о правовом статусе": "Title status records confirmed",
"Открыть отчёт": "Open report",
"Продолжить к тестовой оплате": "Continue to test payment",
"Оформление отчёта пока недоступно.": "Report checkout is not available yet.",
"Проверка конкретной машины": "Specific vehicle check",
"ТЕСТОВЫЙ ПРОВАЙДЕР": "TEST PROVIDER",
"Что доступно до оплаты": "Available before payment",
"Показаны только сведения, подтверждённые предварительной проверкой.": "Only information confirmed by the preliminary check is shown.",
"Остальные записи определяются после запроса провайдера.": "Other records are determined after the provider request.",
"Покрытие источника ограничено; выводы относятся только к найденным записям.": "Source coverage is limited; conclusions apply only to the records found.",
"Защищённый отчёт": "Protected report",
"Повторить получение отчёта": "Retry retrieving the report",
"Демонстрационный сценарий: деньги не списываются.": "Demo scenario: no money is charged.",
"Тестовая оплата": "Test payment",
"Это проверка сценария без реального списания и без платного API-запроса.": "This tests the flow with no real charge and no paid API request.",
"Получить тестовый отчёт": "Get test report",
"Хронология пробега": "Odometer timeline",
"График датированных показаний пробега": "Chart of dated odometer readings",
"История конкретной машины": "History of this vehicle",
"Обнаружена аномалия последовательности пробега. Проверьте исходные показания.": "Odometer sequence anomaly detected. Check the original readings.",
"Фотографии из отчёта": "Report photos",
"Фото из отчёта": "Report photo",
"Тестовый отчёт. Выводы ограничены подтверждёнными событиями источника.": "Test report. Conclusions are limited to events confirmed by the source.",
"Открыт": "Unlocked",
"Ожидает": "Pending",
"Статус запроса обновлён": "Request status updated",
"VIN, объявление Turbo.az или известные вам параметры.": "A VIN, a Turbo.az listing or the details you know.",
"Допустимая альтернатива": "Acceptable alternative",
"Передний дифференциал": "Front differential",
"Задний дифференциал": "Rear differential",
"Октан производителя (AKI, шкала США) пересчитан в АИ по таблице Auto Expert. Рекомендация Auto Expert — не требование производителя.": "The octane is shown as the manufacturer states it (AKI, the US pump scale).",
"Перед покупкой проверьте диагностику и сервисную историю.": "Before buying, check the diagnostics and the service history.",
"Проверьте применимость сервисных кампаний по VIN.": "Check which service campaigns apply by VIN.",
"Проверьте VIN и документы, кузов, холодный запуск и сервисную историю.": "Check the VIN and documents, the body, a cold start and the service history.",
"Сравните две версии из каталога": "Compare two catalog configurations",
"Загрузите разрешённый CSV/JSON как документ. Укажите ownership-csv-v1 или ownership-json-v1 в manifest. Публикация проходит обычную проверку. Секреты и данные аккаунтов запрещены.": "Upload an approved CSV/JSON file as a document. Specify ownership-csv-v1 or ownership-json-v1 in the manifest. Publication goes through the standard review. Secrets and account data are not allowed.",
"Применимость и права · JSON": "Applicability and rights · JSON",
"Загрузить изображение на проверку": "Upload image for review",
"Просмотреть изображение": "View image",
"Сохранить черновик": "Save draft",
"Коммерческие права проверены": "Commercial rights reviewed",
"Локальный просмотр": "Local preview",
"Год «от» не может быть больше года «до».": "Start year can't be later than end year.",
"Проверьте диапазон бюджета и число знаков после запятой.": "Check the budget range and the number of decimal places.",
"Выберите хотя бы один рынок.": "Select at least one market.",
"Исследование пока не запущено: worker не настроен.": "Research has not started: the worker is not configured.",
"Для этого источника требуется разрешение.": "This source requires permission.",
"Сначала подтвердите поколение, кузов, рынок и годы изображения.": "First confirm the image's generation, body style, market and years.",
"Для публикации нужны подтверждённые права на изображение.": "Publishing requires confirmed image rights.",
"Неверный email или пароль.": "Incorrect email or password.",
"Этот email уже зарегистрирован.": "This email is already registered.",
"Нужны права редактора.": "Editor permissions required.",
"Проверенные данные. Понятные выводы. Для правильного выбора.": "Verified data. Clear conclusions. The right choice.",
"Хочу приобрести машину": "I want to buy a car",
"Подберём по бюджету, условиям и вашим приоритетам": "We'll match cars to your budget, conditions and priorities",
"Начать подбор": "Start search",
"VIN, объявление или номер автомобиля": "VIN, listing or license plate",
"Проверить авто": "Check a vehicle",
"Битва поколений": "Generation vs. generation",
"Пары опубликованных версий. Сравните их по своим условиям.": "Pairs of published configurations. Compare them for your conditions.",
"Все сравнения": "All comparisons",
"Бюджет, AZN": "Budget, AZN",
"Как вам удобнее выбирать?": "How would you like to choose?",
"Подобрать по моим условиям": "Find cars for my conditions",
"Подбор машины": "Car finder",
"Сбросить": "Reset",
"Результаты": "Results",
"Подберём машину под вас": "Let's find the right car for you",
"Укажите параметры — покажем подходящие версии и то, что ещё нужно уточнить.": "Enter your criteria — we'll show matching configurations and what still needs clarification.",
"От": "Min.",
"До": "Max.",
"Год выпуска": "Year",
"Выбрать рынки": "Select markets",
"Канал поставки": "Supply channel",
"Официальный дилер AZ": "Authorized dealer (AZ)",
"Другой": "Other",
"Канада": "Canada",
"Корея": "Korea",
"Япония": "Japan",
"Китай": "China",
"Германия": "Germany",
"Франция": "France",
"Италия": "Italy",
"Великобритания": "United Kingdom",
"Страны Залива": "Gulf states",
"Азербайджан": "Azerbaijan",
"Седан": "Sedan",
"Внедорожник / SUV": "SUV / off-roader",
"Кроссовер": "Crossover",
"Хетчбэк": "Hatchback",
"Универсал": "Wagon",
"Купе": "Coupe",
"Минивэн": "Minivan",
"Пикап": "Pickup",
"Бензин без турбины": "Gasoline, naturally aspirated",
"Бензин турбо": "Gasoline, turbo",
"Гибрид HEV": "Hybrid HEV",
"Заряжаемый гибрид": "Plug-in hybrid",
"Электро": "Electric",
"Обычный автомат AT": "Conventional automatic AT",
"Вариатор CVT / IVT": "CVT / IVT",
"Робот DCT / DSG": "Dual-clutch DCT / DSG",
"Механика": "Manual",
"Автомат, тип не знаю": "Automatic, type unknown",
"Передний": "Front",
"Задний": "Rear",
"Полный AWD": "AWD",
"Полный 4WD": "4WD",
"Минимум мест": "Minimum seats",
"Не знаете точный тип?": "Not sure of the exact type?",
"Это нормально. Неизвестные параметры останутся неизвестными — уточним их отдельно.": "That's fine. Unknown details stay unknown — we'll clarify them separately.",
"Город / регион": "City / region",
"Где будете ездить?": "Where will you drive?",
"Надёжность": "Reliability",
"Расходы": "Costs",
"Комфорт": "Comfort",
"Простота ремонта": "Ease of repair",
"Запчасти": "Parts",
"Простор": "Space",
"Безопасность": "Safety",
"Перепродажа": "Resale",
"Оценим только то, для чего есть сопоставимые данные. Неизвестное не получит выдуманный балл.": "We rate only what has comparable data. Unknowns don't get a made-up score.",
"Подходящие варианты": "Matching options",
"Ваш профиль": "Your profile",
"Сначала новее": "Newest first",
"Автомобиль": "Vehicle",
"Доступные характеристики": "Available specs",
"Проверьте версию": "Check the configuration",
"Базовые характеристики подтверждены": "Basic specs confirmed",
"Предпросмотр · 2021–2026": "Preview · 2021–2026",
"Конфигурация из технической базы США, подготовленная к публикации. Показывается только в предпросмотре; сохранение и сравнение для неё пока недоступны.": "Configuration from the US technical database, prepared for publication. Shown in preview only; saving and comparing are not available for it yet.",
"Каталог ещё не подтверждает поколения, комплектации и доступность на рынке AZ. Полные досье требуют дополнительных источников.": "The catalog does not yet confirm generations, trims or availability in the AZ market. Full dossiers require additional sources.",
"Источник": "Source",
"Источники и ограничения": "Sources and limitations",
"Отчёт сохранён": "Report saved",
"Сравнение под ваши условия": "Comparison for your conditions",
"Цена перепродажи, AZN": "Resale price, AZN",
"Топливо, AZN/л": "Fuel, AZN/L",
"Электричество, AZN/kWh": "Electricity, AZN/kWh",
"Пересчитать": "Recalculate",
"Итого владение": "Ownership total",
"Резерв ремонта": "Repair reserve",
"Прочее": "Other",
"Покупка показана отдельно и не прибавляется повторно к потере стоимости. Это ваши допущения, а не оценка рыночной цены.": "The purchase is shown separately and is not added again to depreciation. These are your assumptions, not a market price estimate.",
"Добавьте два или три автомобиля": "Add two or three vehicles",
"Выбрать из каталога": "Choose from catalog",
"Сравнить сохранённые отчёты": "Compare saved reports",
"Следующие варианты": "Next options",
"Госномер": "License plate",
"Избранное": "Favorites",
"Все темы": "All topics",
"Пароль": "Password",
"Повторить": "Try again",
"Можно выбрать до трёх": "You can choose up to three",
"Не удалось выполнить действие. Проверьте соединение и введённые данные.": "Couldn't complete the action. Check your connection and the data you entered.",
"Реестр источников": "Source registry",
"Импорты и проверка": "Imports and review",
"Согласовать": "Approve",
"Отклонить": "Reject",
"Опубликовать": "Publish",
"Возобновить": "Resume",
"Фоновый worker не включён; очередь обрабатывается локальной командой оператора.": "Background worker is off; the queue is processed by a local operator command.",
"Покрытие каталога": "Catalog coverage",
"Изображения на проверке": "Images under review",
"ID источника": "Source ID",
"Уточнить версию": "Refine configuration",
"Одна версия совпадает": "One configuration matches",
"Возможны несколько версий": "Several configurations possible",
"Есть противоречие в параметрах": "Conflicting details",
"Версия ещё не найдена в каталоге": "Configuration not in the catalog yet",
"Этот рынок пока не покрыт каталогом": "This market isn't covered by the catalog yet",
"Отсутствие записи не означает, что такого автомобиля не существует. Параметры автоматически не заменяются.": "A missing record doesn't mean the vehicle doesn't exist. Details are not replaced automatically.",
"Бензин · любой наддув": "Gasoline · turbo or non-turbo",
"Почему этот вариант первый": "Why this option is first",
"По подтверждённым критериям есть равноценные варианты. При равенстве первым показан более новый модельный год, затем порядок по названию.": "Several options are equal on confirmed criteria. Ties are ordered by newer model year, then by name.",
"Разделы профиля машины": "Vehicle profile sections",
"Проверка прав источника": "Source rights review",
"Приостановить новые обновления": "Pause new updates",
"Сохранить решение по правам": "Save rights decision",
"Проверка и исправление фактов": "Fact review and correction",
"Открыть опубликованную запись": "Open published record",
"Исправленная запись JSON · с revision_note": "Corrected JSON record · with revision_note",
"Защитить от автоматических обновлений": "Lock against automatic updates",
"Вернуть предыдущую ревизию": "Restore previous revision",
"Найти недостающие сведения": "Find missing information",
"Автоматический поиск пока не включён. Доступны опубликованные факты и план осмотра.": "Automatic search is not enabled yet. Published facts and the inspection plan are available.",
"Результат поиска проверит редактор перед добавлением в каталог.": "An editor will review search results before they are added to the catalog.",
"В очереди": "Queued",
"Поиск выполняется": "Searching",
"Поиск завершён · нужна проверка": "Search complete · review needed",
"Часть сведений найдена · нужна проверка": "Some information found · review needed",
"Поиск остановлен или недоступен": "Search stopped or unavailable",
"Запросов к источникам": "Source requests",
"Обновить статус": "Refresh status",
"Увеличенный текст": "Large text",
"Доступ к зарядке не подтверждён": "Charging access not confirmed",
"Исходный рынок ещё не выбран": "Original market not selected yet",
"Предпочтения по конструкции требуют уточнения": "Design preferences need clarification",
"Электроэнергия": "Electricity",
"ДВС": "ICE",
"Электромобиль": "Electric vehicle",
"Гибрид": "Hybrid",
"Полный привод 4WD": "Four-wheel drive (4WD)",
"Классический автомат AT": "Conventional automatic AT",
"Вариатор CVT": "CVT",
"Трансмиссия e-CVT": "e-CVT transmission",
"Робот DCT": "Dual-clutch DCT",
"Одноступенчатый редуктор": "Single-speed reduction gear",
"Автомат, тип не уточнён": "Automatic, type not specified",
"Бесступенчатая, тип не уточнён": "Continuously variable, type not specified",
"Автоматизированная, тип не уточнён": "Automated, type not specified",
"Внедорожник": "SUV",
"Классический автомат": "Conventional automatic",
"Вариатор": "CVT",
"Роботизированная коробка": "Automated manual transmission",
"Автомат": "Automatic",
"Подключаемый полный привод": "On-demand AWD",
"Плановое ТО": "Scheduled maintenance",
"Резерв отдельно от расходов": "Reserve kept separate from costs",
"Покрытие ТО неполное: итог нельзя считать полной стоимостью.": "Maintenance coverage is incomplete: the total is not the full cost.",
"Не хватает марки топлива, её цены или применимого расхода.": "Missing fuel grade, fuel price or applicable fuel economy.",
"Для этой силовой установки модель расходов пока не поддерживается.": "The cost model doesn't support this powertrain yet.",
"Уточните силовую установку и долю электрического пробега PHEV.": "Specify the powertrain and the PHEV's share of electric driving.",
"Неизвестен бензин в электрическом режиме PHEV.": "PHEV gasoline use in electric mode is unknown.",
"Укажите сторону измерения расхода и потери, если они ещё не учтены.": "Specify where consumption is measured and any losses not yet included.",
"Нет тарифа зарядки или бытового потребления без автомобиля.": "No charging rate or household usage without the vehicle.",
"Тариф сменился внутри расчётного месяца; нужен порядок распределения по счётчику.": "The rate changed within the billing month; a meter-based allocation method is needed.",
"Нет сценария покупки и перепродажи.": "No purchase and resale scenario.",
"Прочие статьи расходов не заданы.": "Other cost items are not set.",
"Нужна история обслуживания.": "Service history needed.",
"Решение об операции требует осмотра.": "Deciding on this service requires an inspection.",
"Нет цены детали с подтверждённой совместимостью.": "No part price with confirmed compatibility.",
"Нет применимой цены работы.": "No applicable labor rate.",
"Конфликт цен: выберите применимого поставщика.": "Price conflict: choose the applicable supplier.",
"Конфликт регламентов: требуется редакционная проверка.": "Schedule conflict: editorial review required.",
"Пересекающиеся работы требуют общего предложения СТО.": "Overlapping jobs need a combined quote from the shop."
};
export const pickText = (language, ru, az, en) => language === 'az' ? az : language === 'en' ? (en ?? EN[ru] ?? ru) : ru;
// the device language: en -> EN, ru -> RU, az -> AZ, any other -> EN
export function deviceLanguage(languages = (typeof navigator === 'undefined' ? [] : navigator.languages || [navigator.language])) {
  for (const tag of languages || []) {
    const code = String(tag || '').toLowerCase().split('-')[0];
    if (['en', 'ru', 'az'].includes(code)) return code;
  }
  return 'en';
}
