"""Translations of the catalogue's Russian texts into Azerbaijani and English.

The Russian text in catalog/*.json and catalog/components/*/*.json is the source of truth.

  catalog/i18n/glossary.json      terms, protected words, units (approved by the owner)
  catalog/i18n/phrases/*.json     the translations people write and review:
                                    "texts":     whole texts, matched exactly
                                    "fragments": pieces of notes / generation labels / component
                                                 names, matched inside texts of the listed kinds
                                                 ("ru" literal or "re" regex with \\1 groups)
  catalog/i18n/source.json        every Russian text to translate (key, kind, text) — generated
  catalog/i18n/{az,en}.json       key = sha256 of the Russian text with whitespace collapsed (the
                                  same key as the app's content_translations), value = {ru, text,
                                  kind, status, method} — generated by `build`

A key whose Russian text no longer occurs in the catalogue is kept with status "stale" (never
dropped silently); a Russian text the phrases cannot translate is reported as missing.
Only texts with Cyrillic letters (and the MIIT fuel-cycle labels) are translated; codes, Chinese
trim names and numbers are shown as they are. Notes are translated per segment (" | ").

  python tools/i18n.py build   -> source.json, az.json, en.json + check (exit 1 on missing/problems)
  python tools/i18n.py check   -> stale / missing / validation report only
"""
import glob
import hashlib
import json
import os
import re
import sys
import unicodedata

TOOLS = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(TOOLS, '..', 'catalog'))
I18N = os.path.join(ROOT, 'i18n')
LANGS = ('az', 'en')
CYR = re.compile(r'[А-Яа-яЁё]')
HAN = re.compile(r'[一-鿿]+')
NUM = re.compile(r'\d+(?:[.,]\d+)?')


def key_of(text):
    return hashlib.sha256(' '.join(str(text or '').split()).encode('utf-8')).hexdigest()


def norm(text):
    return unicodedata.normalize('NFC', ' '.join(str(text or '').split()))


def L(p):
    return json.load(open(p, encoding='utf-8'))


def W(p, d):
    with open(p, 'w', encoding='utf-8', newline='\n') as f:
        json.dump(d, f, ensure_ascii=False, indent=1, sort_keys=True)
        f.write('\n')


# ---- what to translate ----------------------------------------------------------------

def texts():
    """key -> (kind, russian text) for every translatable text, in catalogue order."""
    out = {}

    def add(kind, value, also_chinese=False):
        if not isinstance(value, str):
            return
        if CYR.search(value) or (also_chinese and '工信部' in value):
            value = norm(value)
            out.setdefault(key_of(value), (kind, value))

    def issues(items):
        for i in items or []:
            add('cn_issue', i.get('text'))
            add('cn_scope_note', i.get('scope_note'))
            add('cn_review_car', i.get('review_car'))

    for name in sorted(os.listdir(ROOT)):
        if not name.endswith('.json'):
            continue
        d = L(os.path.join(ROOT, name))
        issues(d.get('known_issues'))
        for b in d.get('buyer_checks') or []:
            add('cn_buyer_check', b)
        for seg in (d.get('notes') or '').split(' | '):
            add('cn_note', seg.strip())
        add('cn_generation', d.get('generation'))
        add('cn_status', d.get('status_china'))
        add('cn_hybrid_system', d.get('hybrid_system'))
        add('cn_fuel_cycle', (d.get('fuel_l_100km') or {}).get('cycle'), also_chinese=True)
        closest = d.get('closest_official') or {}
        add('cn_closest_trim', closest.get('trim'))
        add('cn_closest_why', closest.get('why'))
    for sub in ('engines', 'transmissions', 'hybrid_systems'):
        for path in sorted(glob.glob(os.path.join(ROOT, 'components', sub, '*.json'))):
            c = L(path)
            issues(c.get('known_issues'))
            add('cn_component_name', c.get('name'))
            add('cn_component_note', c.get('note'))
            for v in (c.get('specs') or {}).values():
                for x in v if isinstance(v, list) else [v]:
                    add('cn_component_spec', x)
    return out


# ---- phrases -> translations ----------------------------------------------------------

def phrases():
    whole, literal, regex = {}, [], []
    for path in sorted(glob.glob(os.path.join(I18N, 'phrases', '*.json'))):
        data = L(path)
        for e in data.get('texts', []):
            ru = norm(e['ru'])
            if ru in whole:
                raise SystemExit(f'{os.path.basename(path)}: text twice: {ru[:60]}')
            whole[ru] = {lang: norm(e[lang]) for lang in LANGS}
        for e in data.get('fragments', []):
            kinds = set(e['kinds'])
            if 're' in e:
                regex.append((kinds, re.compile(e['re']), {lang: e[lang] for lang in LANGS}))
            else:
                literal.append((kinds, norm(e['ru']), {lang: e[lang] for lang in LANGS}))
    literal.sort(key=lambda x: -len(x[1]))
    return whole, literal, regex


def translate(kind, ru, lang, book):
    whole, literal, regex = book
    if ru in whole:
        return whole[ru][lang], 'text'
    out = ru
    for kinds, frag, tr in literal:
        if kind in kinds and frag in out:
            out = out.replace(frag, tr[lang])
    for kinds, rx, tr in regex:
        if kind in kinds:
            out = rx.sub(tr[lang], out)
    if CYR.search(out) or (kind == 'cn_fuel_cycle' and '工信部' in out):
        return None, None
    return norm(out), 'fragments'


# ---- checks ---------------------------------------------------------------------------

def _numbers(text):
    text = re.sub(r'(\d),(\d{3})\b', r'\1\2', text)  # 70,000 -> 70000
    return sorted(n.replace(',', '.') for n in NUM.findall(text))


def problems(ru, text, lang, g):
    out = []
    if not text or not text.strip():
        return ['empty']
    allowed = {tuple(_numbers(ru)), tuple(_numbers(re.sub(r'(\d+)\s*тыс\.', r'\g<1>000', ru)))}
    if tuple(_numbers(text)) not in allowed:
        out.append(f'numbers {_numbers(ru)} -> {_numbers(text)}')
    for term in g['do_not_translate']:
        if term in ru and term not in text:
            out.append(f'protected term lost: {term}')
    translated = g.get('translated_chinese', {})
    for han in HAN.findall(ru):
        rest = han
        for term in sorted(translated, key=len, reverse=True):
            rest = rest.replace(term, '')
        if rest and rest not in text and han not in text:
            out.append(f'chinese label lost: {han}')
    if CYR.search(text):
        out.append('cyrillic left')
    words = re.findall(r'[a-zəıöüçşğ]{4,}', text)
    if lang == 'az' and len(words) >= 3 and not re.search(r'[əıöüçşğ]', text):
        out.append('no azerbaijani letters')
    return out


def build(verbose=True):
    src = texts()
    W(os.path.join(I18N, 'source.json'), {k: {'kind': kind, 'ru': ru} for k, (kind, ru) in src.items()})
    book = phrases()
    g = L(os.path.join(I18N, 'glossary.json'))
    report = {'source': len(src), 'glossary': g['version']}
    errors = 0
    for lang in LANGS:
        path = os.path.join(I18N, f'{lang}.json')
        old = L(path) if os.path.exists(path) else {}
        data = {}
        missing = []
        for k, (kind, ru) in src.items():
            text, method = translate(kind, ru, lang, book)
            if text is None:
                missing.append(k)
                continue
            data[k] = {'ru': ru, 'text': text, 'kind': kind, 'status': 'ok', 'method': method}
        stale = {k: {**v, 'status': 'stale'} for k, v in old.items() if k not in src}
        data.update(stale)
        bad = {k: problems(v['ru'], v['text'], lang, g) for k, v in data.items() if v['status'] == 'ok'}
        bad = {k: p for k, p in bad.items() if p}
        W(path, data)
        report[lang] = {'translated': len(data) - len(stale), 'stale': len(stale), 'missing': len(missing),
                        'problems': len(bad)}
        errors += len(missing) + len(bad)
        if verbose:
            for k in missing[:40]:
                print(f'  missing {lang}: [{src[k][0]}] {src[k][1][:110]}')
            for k, p in list(bad.items())[:60]:
                print(f'  problem {lang}: {data[k]["ru"][:70]} -> {p}')
    print(json.dumps(report, ensure_ascii=False))
    return report, errors


if __name__ == '__main__':
    cmd = sys.argv[1] if len(sys.argv) > 1 else 'build'
    if cmd in ('build', 'check'):
        sys.exit(1 if build()[1] else 0)
    raise SystemExit(__doc__)
